Refo 26
RefugeeOne699/refugee-one pull request #12
Opened 2023-03-13 18:18 UTC by 10RE

2023-03-23 01:07 UTC, makersmelx requested changes
please help to resolve the conflict first. After that, we may need to let Neha @nehakumari2307  take a review at the appearance.

2023-03-23 01:07 UTC, makersmelx commented on src/components/Navbar.jsx
> +
i would prefer to set style by adding tailwind `className` by here https://github.com/negomi/react-burger-menu#custom-id-andor-classnames

for color, if there is no place to set className,  please refer to https://tailwindcss.com/docs/customizing-colors

2023-03-27 21:07 UTC, 10RE commented on src/components/Navbar.jsx
> +  });
i don't get it, what do you mean by flex class @makersmelx

2023-03-29 18:50 UTC, makersmelx requested changes
In the mobile view, seems the menu occupies some of the spaces, which is not expected. the main content should occupy the full page.
![image](https://user-images.githubusercontent.com/13199342/228638074-f5b198dc-2e89-4a82-a36e-0c98deb2f566.png)


In the PC view, when the user is not logged in, we have a blank on the left side, which is also not expected
![image](https://user-images.githubusercontent.com/13199342/228638509-21ea0160-bdec-441b-9078-7f083d7fb441.png)

2023-03-29 19:05 UTC, makersmelx requested changes

2023-03-29 19:05 UTC, makersmelx commented on src/components/Navbar.jsx
> +        path: "",
add a `todo` for pages that are not merged/created yet

2023-03-30 00:59 UTC, makersmelx requested changes
please add a todo in the class related props of the hamburger menu
`todo: fix dark mode compatibility`

the gap is not expected
![image](https://user-images.githubusercontent.com/13199342/228700314-e2f72ef5-3d62-48ee-a7dd-06e2ea18380b.png)

still not in the center
![image](https://user-images.githubusercontent.com/13199342/228700360-bb0ae8ba-1b6e-43b5-902f-db8fb02e96e2.png)

2023-03-30 03:00 UTC, makersmelx approved these changes

2023-03-30 03:12 UTC, merged